In [1]:
import numpy as np
import pandas as pd

In [2]:
# Importing dataset
st=pd.read_csv("student_exam_data_v1.csv")
st

,study_hours,exam_score
0,4.4,59
1,9.6,98
2,7.6,82
3,6.4,69
4,2.4,42
...,...,...
495,4.2,55
496,6.3,69
497,1.7,44
498,9.8,95


In [3]:
# Check datatypes
st.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 500 entries, 0 to 499
Data columns (total 2 columns):
 #   Column       Non-Null Count  Dtype  
---  ------       --------------  -----  
 0   study_hours  500 non-null    float64
 1   exam_score   500 non-null    int64  
dtypes: float64(1), int64(1)
memory usage: 7.9 KB


In [4]:
# Check null values
st.isnull().sum()

,0
study_hours,0
exam_score,0


In [5]:
x=st["study_hours"].value_counts()
x

,count
study_hours,
9.7,13
1.8,13
6.7,12
3.9,11
9.1,11
...,...
9.3,2
5.3,2
8.6,2


In [6]:
y=st["exam_score"].value_counts()
y

,count
exam_score,
79,17
45,17
83,16
89,12
74,12
...,...
32,3
46,3
99,2


In [7]:
#Feature engineering
x=st[["study_hours"]] # Feature
y=st[["exam_score"]]  # Target

In [8]:
# Dataset split into train and test data
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,train_size=0.7,random_state=42)

In [9]:
# Linear regression
from sklearn.linear_model import LinearRegression
l=LinearRegression()
l.fit(x_train,y_train)

LinearRegression()

In [10]:
y_prediction=l.predict(x_test)
y_prediction

array([[73.94009125],
       [83.87427562],
       [39.50158542],
       [50.09804875],
       [89.83478624],
       [56.05855937],
       [36.85246959],
       [49.43576979],
       [40.16386438],
       [81.88743875],
       [77.913765  ],
       [56.05855937],
       [58.70767521],
       [54.0717225 ],
       [36.85246959],
       [80.56288083],
       [56.72083833],
       [71.95325437],
       [60.03223312],
       [89.17250729],
       [62.68134896],
       [72.61553333],
       [88.51022833],
       [36.85246959],
       [81.22515979],
       [73.94009125],
       [40.16386438],
       [76.58920708],
       [73.27781229],
       [38.1770275 ],
       [94.47073895],
       [86.52339145],
       [40.82614333],
       [48.77349083],
       [79.23832291],
       [42.15070125],
       [40.82614333],
       [81.88743875],
       [44.79981708],
       [56.72083833],
       [79.23832291],
       [69.30413854],
       [89.17250729],
       [74.60237021],
       [91.82162312],
       [40

In [11]:
# Actual test value
y_test

,exam_score
361,71
73,80
374,38
155,47
104,89
...,...
266,76
23,59
222,36
261,94


In [12]:
# Accuracy of prediction
from sklearn.metrics import r2_score
r2_score(y_test,y_prediction)

0.9684862125086858

In [13]:
st["study_hours"].unique()

array([4.4, 9.6, 7.6, 6.4, 2.4, 1.5, 8.8, 7.4, 1.2, 9.7, 8.5, 2.9, 2.6,
       2.7, 3.7, 5.7, 4.9, 3.6, 6.5, 2.3, 4.3, 5.1, 8.1, 2.8, 5.6, 6.3,
       1.4, 2.5, 1.6, 9.5, 8.3, 1.9, 7.2, 5. , 2.1, 5.5, 1.3, 9.2, 3.3,
       7. , 3.8, 5.9, 8. , 9.1, 9.3, 1.8, 3.9, 4.5, 3.4, 4.2, 3.5, 8.2,
       1.7, 9.9, 1. , 7.9, 2. , 6.6, 4. , 6.7, 9. , 5.2, 7.8, 6.1, 5.4,
       4.8, 3.2, 4.7, 3.1, 9.4, 8.4, 8.7, 1.1, 3. , 7.3, 5.8, 7.1, 6.8,
       2.2, 4.1, 8.9, 6.9, 6. , 7.5, 7.7, 8.6, 9.8, 6.2, 5.3, 4.6])

In [14]:
# check manual study hours with exam_score
l.predict(np.array([[8.3]]))

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([[83.87427562]])

In [16]:
l.predict(np.array([[10]]))

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([[95.13301791]])